language: python
python:
  - "3.7.9"
install:
  - pip install flask

script:
  - python -m unittest -v test
# Definir o Deploy no Heroku
# deploy:
#   provider: heroku
#   api_key: $HEROKU_API_KEY
#   edge: true 
#   app: devops2-leonardodeassis
#   on:
#      branch: master
