os: linux
dist: xenial
language: python
python:
  - "3.7.9"

before_install:
        - openssl aes-256-cbc -K $encrypted_272e41cf8212_key -iv $encrypted_272e41cf8212_iv
          -in lab-devops01-64cb773ae3dc.json.enc -out lab-devops01-64cb773ae3dc.json -d
addons:
  sonarcloud:
    organization: leoanrdodeassis
    token: ${SONAR_TOKEN}
jobs:
    include:      
      - stage: build
        install:
          - pip install flask flask-wtf coverage 
        script: 
         - sonar-scanner || travis_terminate 1;
         - coverage xml app.py || travis_terminate 1;
         - coverage report app.py || travis_terminate 1;
         
      - stage: STAGE Deploy
        script: skip
        deploy: &heroku 
          provider: heroku
          api_key: $HEROKU_API_KEY
          edge: true 
          app: devops2-leonardodeassis
          strategy: api
 
      - stage: STAGE Test
        script: curl https://devops2-leonardodeassis.herokuapp.com

      - stage: PROD Deploy
        script: skip 
        deploy:
          provider: gae
          keyfile: lab-devops01-64cb773ae3dc.json
          project: lab-devops01

      - stage: Prod Test
        script: curl https://lab-devops01.uc.r.appspot.com/

        
