os: linux
dist: xenial
language: python
python:
  - "3.7.9"
install:
  - pip install flask

jobs:
    include:      
      - stage: build
        script: python -m unittest -v test || travis_terminate 1;
 
      - stage: STAGE Deploy
        script: skip
        deploy: &heroku 
          provider: heroku
          api_key: $HEROKU_API_KEY
          edge: true 
          app: devops2-leonardodeassis
          strategy: api
 
      - stage: STAGE Test
        script: curl https://devops2-leonardodeassis.herokuapp.com

      - stage: PROD Deploy
        script: skip 
        deploy:
          <<: *heroku
          provider: gae
          project: lab-devops01
          keyfile: lab-devops01-64cb773ae3dc.json.enc
      - stage: Prod Test
        script: curl https://lab-devops01.uc.r.appspot.com/
before_install:      
- openssl aes-256-cbc -K $encrypted_272e41cf8212_key -iv $encrypted_272e41cf8212_iv
  -in lab-devops01-64cb773ae3dc.json.enc -out ~/lab-devops01-64cb773ae3dc.json -d

